### ISSUE TITLE
Unify our REST API

### ISSUE THREAD

**Issue by ktrieu** [UWmathNEWS/slugline-web#23]
Right now, we have two versions of our API library, a hooks-based version and a Promise-based version.

This introduces two problems:
- We have to duplicate our code across these two versions
- We don't actually have the Promise-based versions so people just stick `axios` into components when they need it.

We can fix both these problems by making the Promise-based version the authoritative versions of the API, and introducing some hooks that will wrap the Promise-based versions for use at the top-level in components.

Currently, I believe we need the following two:

```
interface UseGetHook <TResp, TError extends APIError> {
  data: TResp | undefined;
  error: TError | undefined;
  status_code: number | undefined;
  requestState: RequestState;
}

// if we have to get based on an ID, we can pass a callback that wraps the promise function and an ID
const useGet = <TResp, TError>(getAsync: () => Promise<APIResponse<TResp, TError>>) => UseGetHook<TResp, TError extends APIError> 

// we can be really fancy and make a type guard to tell these apart
interface MutateHookSuccess<TResp> {
  status_code: 200
  data: TResp
}

interface MutateHookError<TError> {
  status_code: number
  error: TError
}

interface UseMutateHook<TArgs, TResp, TError> {
   mutate: (TArgs) => Promise<MutateHookSucccess<TResp>> | Promise<MutateHookError<TError>>
   requestState: RequestState
}

const useMutate = <TArgs, TResp, TError>(mutate: (TArgs) => <APIResponse<TResp, TError>>) => UseMutateHook<TArgs, TResp, TError>
```

These should be able to replace API calls everywhere and let us take care of them in one central place.

**Comment by tyxchen** [comment]
A few thoughts:

1. Wha's an example of using the getAsync argument to useGet/the mutate argument to useMutate?
2. I'd like to see the hooks return an array instead of an object; it makes assigning to variables easier, and also lets us destructure while not in a const/let statement. 
3. On the note of arrays, I don't think useGet needs to return a status code — it should be included in the error object. 
4. Something I've been thinking of is also having a "delayed" get hook in the style of mutable hooks. For example,

```
const [callApi,] = useDelayedGet("url");
...
const data = await callApi();
```

This would be useful for things like username validation in ProfileForm, especially because we can take advantage of the requestState being returned to show the user that we are checking (something that is currently quite clunky to implement with our existing methods).

**Comment by ktrieu** [comment]
> What's an example of using the getAsync argument to useGet/the mutate argument to useMutate?

It'd be something like this:
```
const getIssue(id: number) => Promise<APIResponse<Issue>> {
  // internet stuff, whatever
}

const { id } = getParams()
// not entirely satisfied with this syntax
const [issue, issueError] = useGet(() => { getIssue(id })

const updateIssue(id: number, issue: Issue) => Promise<APIResponse<Issue>> {
  // different internet stuff
}

const [updateIssue,] = useMutate(updateIssue)
await updateIssue(id, { issue stuff})
```

> I'd like to see the hooks return an array instead of an object; it makes assigning to variables easier, and also lets us destructure while not in a const/let statement.

So the thing about arrays is they get unwieldy when you're returning more than like two things. I think we should do what Apollo does and return `[data/mutation function, infoObject]` where the `infoObject` has the error, request state, whatever.

> On the note of arrays, I don't think useGet needs to return a status code — it should be included in the error object. 

That's the way we have it now. I'd be fine with keeping it that way.

> Something I've been thinking of is also having a "delayed" get hook in the style of mutable hooks. For example,

This made me realize the whole get/mutate distinction is wrong, its more like eager/lazy, where eager takes a no argument function and runs as soon as it can, while the lazy version takes a function with arguments and exposes a function with the same arguments.

**Comment by tyxchen** [comment]
Hmm, so the idea is that we have base-level Promise-oriented API methods, and we can wrap those in a `useApi`/`useLazyApi` hook for state? Sounds fine with me, as long as we can develop a common interface and naming convention for the methods. So perhaps

```ts
interface APIMethodConfig {
  search?: string;
  sort?: string;
}

//
// Methods
//

function apiMethod<T extends APIResponseSuccess>(method: Method, baseUrl: string, pk: string | number, config: APIMethodConfig = {}) => Promise<T> {
  ...
}
function apiMethod<D, T extends APIResponseSuccess>(method: Method, baseUrl: string, pk: string | number, data: D, config: APIMethodConfig = {}) => Promise<T> {
  ...
}
// Example
const getIssue = (id: number): Promise<...> => apiMethod("get", "issue", id);

//
// Hooks
//

const useApi = <A, TResp, TError>(method: (...props: A) => Promise<TResp>, ...props: A): UseAPIHook<TResp, TError> => ...;
const useLazyApi = <A, TResp, TError>(method: (...props: A) => Promise<TResp>): UseLazyAPIHook<A, TResp, TError> => ...;
// Example
const [issue, issueError] = useApi(getIssue, id);
const [updateIssue, updateIssueInfo] = useLazyApi(patchIssue, id);
```

On naming, I propose that we go for a namespaced approach. I'm not sure how the typings will work out, but here's what I have in mind:

```ts
// Get a list of issues
const listIssues = api.issues.list();
// Get a specific issue
const myIssue = api.issues.get(1);
// We can also create an issue:
api.issues.create(2);
// Or update an issue:
api.issues.update(1, ...);
// Or delete an issue:
api.issues.delete(1);

// We can also have nested namespaces
const myArticle = api.issues.get(1).articles.get(1); // or myIssue.articles.get(1) to save an extra network request
```

This might require experimenting with proxies, but the advantage is that we could possibly be able to automatically generate an API interface with correct typings and whatnot from API documentation alone.

**Comment by ktrieu** [comment]
I don't think we have to go too crazy with the API bindings, since our API surface is pretty small and I don't anticipate it becoming that large. It'll be mostly CRUD stuff, with maybe a few custom actions here and there. DRF doesn't actually natively support nested routes anyway, which is why we sort of emulate them server side.

I'm think we'll have a default endpoint class that handles the basic REST methods, and then you can extend it if you want for custom actions or whatever. Will have a PR soon to demonstrate.
