### ISSUE TITLE
Certain private routes don't load properly in dev server

### ISSUE THREAD

**Issue by tyxchen** [UWmathNEWS/slugline-web#64]
**Describe the bug**
When trying to access the profile or admin routes from either a direct link or via an HMR update with the default webpack dev server setup (NOT our custom SSR server), the routes get stuck in the loading stage.

**To Reproduce**
1. Run `npm start`
2. Load `localhost:3000/dash/admin` or `localhost:3000/dash/profile`. You will need to be logged in beforehand.
3. Note perpetual spinner
4. Click "Admin" or "Profile" in the header. Note the page loads properly now.
5. (optional) Make changes in a source file and save.
6. (optional) Go back to browser and note perpetual spinner again.

**Expected behavior**
`UserList` or `ProfileForm` respectively should be displayed instead of a spinner.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium 83 and Firefox 77

**Additional context**
- It's not actually stuck in trying to load data --- no errors are being thrown, and if you inspect the HTML you'll see that the appropriate components are already rendered. However, `PrivateRoute` is stuck thinking it's in a loading state.
- This seems to be limited to routes with components that directly depend on the `useAuth()` hook. Calling `useAuth()` through another hook, e.g. `useAPILazyUnsafe()`, does not appear to trigger the issue.
- I've tracked the bug to 9a15855, with 5f90d0a being the last good revision. Will post more context as I debug.

Marking as P1 as this affects development.

**Comment by tyxchen** [comment]
Ok, so it looks as though I was mistaken. 9a15855 happens to be the commit where we removed caching user info in localStorage, and in fact the bug is present before 5f90d0a if localStorage is cleared. Further investigation shows that the issue in the admin route dates to fa4fcca, with 15b53b9 being the last good rev. So this appears to be an issue with loading users in `AuthProvider` without hitting localStorage. This is further supported by the fact that fa4fcca is the commit where we moved the admin and profile routes under `routes/Dash`; resulting in nested `PrivateRoute`s, which appears to have been one trigger.

However, it doesn't explain why the admin page loads fine in 15b53b9 but not the profile page. My best guess at this moment is that `PrivateRoute` does not like having descendants depend on `useAuth()` when it misses localStorage.

Adding to web project as this could massively affect other components.

**Comment by tyxchen** [comment]
I've tracked down the regression in the profile page to stemming from 658917c in #13; e2888f5 is the last good revision. 

@ktrieu do you think you could take a look at this? The changes in that commit seem to be quite minor, and yet they appear to have messed everything up?

**Comment by ktrieu** [comment]
Well at least the principles of causality still hold, after removing each line of code in https://github.com/UWmathNEWS/slugline-web/commit/e2888f5f4cae9180fa9b48a3dd2cf8ddf62e0d4c, it is the lines in `ProfileForm` that are causing the problem. Hell if I know why, though.
