### ISSUE TITLE
Creating a new user after opening an existing user will trigger a username query

### ISSUE THREAD

**Issue by tyxchen** [UWmathNEWS/slugline-web#70]
**Describe the bug**
See title

**To Reproduce**
1. Go to user panel
2. Click on an existing user to open the user modal
3. Exit the modal
4. Click the "New User" button to open a blank user modal
5. Check the Django server (or your browser's network inspection tool). Note username query request made to the username of the previously opened user.

**Expected behavior**
No requests should be made

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 77

**Comment by ktrieu** [comment]
Looks like it fixes it. LGTM.

@biped-mathnews, I can add you as a collaborator so you don't have to fork the repo.
